### ISSUE TITLE
PID TypeError

### ISSUE THREAD

**Issue by godzilla-but-nicer** [pmediano/syndisc#1]
Looks like dit changed its BasePID class a few months ago and now _compute() no longer takes any arguments. Instead the reds and pis are stored as attributes of the class. Doesn't seem too big a change and I'll try to get to it in the next couple of days on my fork. Just thought I'd let you know (never done one of these before)
![Screenshot from 2020-05-20 19-20-09](https://user-images.githubusercontent.com/61129239/82506960-08840900-9acf-11ea-8ef5-0f57bc425009.png)

**Comment by pmediano** [comment]
Closed by #5
