### ISSUE TITLE
Bug that might affect users: Incompatibility forced by setup.py

### ISSUE THREAD

**Issue by Abzinger** [pmediano/syndisc#4]
In `setup.py: line 15` the allowed `networkx` package versions to be installed are between 2.0 and 2.3 (included). However, `dit` package requires `networkx` package version 2.6 or newer. This throws an error during installation.  

This can be fixed, for example, by changing `setup.py: line 15` to `"networkx>=2.6,<2.7"`

Cheers,
Abed

**Comment by pmediano** [comment]
Hey Abed,

Thanks for picking this up! (And sorry for the long delay.) We just updated a few things to make the package compatible with the latest pip-installable dit and networkx (see #5 ), so it should work out of the box now. Thanks for the suggestion!

Cheers,
P
